[package]
name = "no_macro_bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
statig = { path = "../../../statig", features = [] }
rand = "*"
